// Offline snapshot of estimated Internet users by language (connected L1 + L2 speakers).
// Ordering adapted from OBDILCI V6, 26 June 2025: RESULTS column D (INTERNAUTES L1+L2).
// OBDILCI, CC BY-SA 4.0: https://creativecommons.org/licenses/by-sa/4.0/
// https://www.obdilci.org/wp-content/uploads/2025/07/ResultsV6.xlsx
// https://www.obdilci.org/projects/main/
// Changes: map Chinese/Arabic macro-languages to zh-CN/ar and Tagalog to fil.
// Split Malay (msa) between id/ms and Serbo-Croatian (hbs) between sr/hr/bs without duplicating totals.
// Split weights: CLDR 48 territory population × language share × latest available 2022–2024 Internet usage rate.
// Icelandic uses the same weighted estimate; sr/XK has no rate in that period and is omitted from the weights.
// These splits approximate macro-language populations, including members without separate YouTube UI languages.
// https://raw.githubusercontent.com/unicode-org/cldr/release-48/common/supplemental/supplementalData.xml
// World Bank IT.NET.USER.ZS (ITU), retrieved 14 September 2026:
// https://api.worldbank.org/v2/country/all/indicator/IT.NET.USER.ZS?format=json&date=2022:2024&per_page=2000
// Each multilingual user can count in multiple languages; regional/script variants follow all 74 core languages.
// YouTube UI codes: https://gist.github.com/insin/449a4734490e62941fabf1f27c09cb99
export const INSIGHTS_LANGUAGES = [
	"zh-CN",
	"en",
	"es",
	"ar",
	"hi",
	"ru",
	"fr",
	"pt",
	"id",
	"bn",
	"de",
	"ja",
	"ur",
	"tr",
	"fil",
	"fa",
	"vi",
	"it",
	"th",
	"ko",
	"mr",
	"te",
	"ta",
	"pl",
	"ms",
	"uk",
	"gu",
	"sw",
	"kn",
	"uz",
	"my",
	"nl",
	"ro",
	"zu",
	"or",
	"pa",
	"ml",
	"az",
	"ne",
	"kk",
	"af",
	"sv",
	"am",
	"el",
	"hu",
	"km",
	"cs",
	"si",
	"ca",
	"iw",
	"as",
	"sr",
	"sk",
	"bg",
	"hr",
	"da",
	"sq",
	"no",
	"fi",
	"mn",
	"ky",
	"bs",
	"be",
	"ka",
	"gl",
	"hy",
	"lo",
	"lt",
	"lv",
	"sl",
	"mk",
	"eu",
	"et",
	"is",
	"en-IN",
	"en-GB",
	"zh-TW",
	"zh-HK",
	"es-419",
	"es-US",
	"fr-CA",
	"pt-PT",
	"sr-Latn",
] as const;
